#! /bin/bash
#BSUB -q medium
#BSUB -n 80
#BSUB -e %J.err
#BSUB -o %J.out

cd $LS_SUBCWD
NP=`cat $LSB_DJOB_HOSTFILE | wc -l`
echo $NP > hostname
cat $LSB_DJOB_HOSTFILE | sort | uniq -c >> hostname

#Change environment variables for CP2K_kit and deepmd-kit
export OMP_NUM_THREADS=1
export PYTHONPATH=/home/lujunbo/bin:$PYTHONPATH
export PATH=/home/lujunbo/bin/CP2K_kit/bin:$PATH
export PATH=/home/lujunbo/bin/deepmd-kit/bin:$PATH

CP2K_kit input.inp > out
