#! /bin/bash
#PBS -q medium
#PBS -l nodes=1:ppn=12
#PBS -N deepmd

cd $PBS_O_WORKDIR
NP=`cat $PBS_NODEFILE | wc -l`
echo $NP > hostname
cat $PBS_NODEFILE | sort | uniq -c >> hostname

#Change environment variables for CP2K_kit and deepmd-kit
export OMP_NUM_THREADS=1
export PYTHONPATH=/home/lujunbo/bin:$PYTHONPATH
export PATH=/home/lujunbo/bin/CP2K_kit/bin:$PATH
export PATH=/home/lujunbo/bin/deepmd-kit/bin:$PATH

CP2K_kit input.inp > out
